version: build {build} {branch}

os: Visual Studio 2019

clone_depth: 1

install:
  - ps: |
      Add-Type -AssemblyName System.IO.Compression.FileSystem
      if (!(Test-Path -Path "C:\ant\apache-ant-1.10.7" )) {
        (new-object System.Net.WebClient).DownloadFile(
        'https://archive.apache.org/dist/ant/binaries/apache-ant-1.10.7-bin.zip',
          'C:\ant-bin.zip'
        )
        [System.IO.Compression.ZipFile]::ExtractToDirectory("C:\ant-bin.zip", "C:\ant")
      }
  - cmd: SET JAVA_HOME=C:\Program Files\Java\jdk13
  - cmd: SET PATH=C:\ant\apache-ant-1.10.7\bin;%JAVA_HOME%\bin;%PATH%
  - cmd: SET IVY_CACHE_DIR=C:\ivy
  - cmd: echo %USERPROFILE%
  - cmd: echo %PATH%
  - cmd: java -version

build_script:
  - ant build

test_script:
  - ant unit-tests

on_finish:
  - ps: |
      $url = "https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)"
      $file = '.\junit\TESTS-TestSuites.xml'
      $webclient = New-Object 'System.Net.WebClient'
      # uploads currently fail because of many tests (https://github.com/appveyor/ci/issues/2084)
      try { $webclient.UploadFile($url, (Resolve-Path $file)) } catch { $_ }
cache:
  - C:\ant
  - C:\ivy
