os: Windows Server 2012

version: '{build}'

skip_commits:
  files:
    - PureEdgeSim/examples/*

branches:
  only:
    - master

init:
  - git config --global core.autocrlf true
  
build_script:
  - mvn clean package --batch-mode -DskipTest
  
test_script:
  - mvn clean verify --batch-mode

cache:
  - C:\maven\
  - C:\Users\appveyor\.m2